
indent: '    '
modifyLineBreaks: 1
maxBlankLines: 2

blankLineBeforeEnvironments:
  - section
  - subsection
blankLineBeforeEnvironmentRules:
  default:
    before: 1

blankLineAfterEnvironments:
  - section
  - subsection
  - itemize
  - enumerate
  - align
blankLineAfterEnvironmentRules:
  section:
    after: 2

# remove spaces after opening or before closing math env.
modifyLineBreaks:
  removeSpacesInInlineMath:
    after:
      - pattern: '\$(\s*)([^\$\\]+?)(\s*)\$'
        replace: '$\2$'
      - pattern: '\\\\\((\s*)([^\\)]+?)(\s*)\\\\\)'
        replace: '\\(\2\\)'
      - pattern: '\\\\\[(\s*)([^\\]]+?)(\s*)\\\\\]'
        replace: '\\[\2\\]'

lookForAlignDelims: 1
trailingComments: 1
trailingBlankLine: 1

